/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.visionlab.faceengine;

final class Point {

    private transient boolean swigCMemOwn;

    private transient long swigCPtr;

    Point(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    public Point() {
        this(FaceEngineJNI.new_Point__SWIG_0(), true);
    }

    public Point(int x, int y) {
        this(FaceEngineJNI.new_Point__SWIG_1(x, y), true);
    }

    static long getCPtr(Point obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected void finalize() throws Throwable {
        delete();
        super.finalize();
    }

    private synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                FaceEngineJNI.delete_Point(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public int getX() {
        return FaceEngineJNI.Point_x_get(swigCPtr, this);
    }

    public void setX(int value) {
        FaceEngineJNI.Point_x_set(swigCPtr, this, value);
    }

    public int getY() {
        return FaceEngineJNI.Point_y_get(swigCPtr, this);
    }

    public void setY(int value) {
        FaceEngineJNI.Point_y_set(swigCPtr, this, value);
    }

}
